language: node_js
node_js: node
deploy:
  provider: heroku
  api_key: 2f633845-04f2-42f3-8180-e636a8f6b828
  secure: jUw8BmTXPa5LpArisUaL2MF6JRtuuJcaRHPu7b+74QM4FZ0C+OB1boJIXJ4k0Kbn7snBaQB2lZtQ7l+2ozc+Tx40XSOH6ULsuSGS7kx8asEMG87vNfT54HSCu47GbNmL+nCU6muMko2VawpzNMF2tgeeqZTN7XlOkkXmRPALjXoczJuVjs/HAh8axd5lTikn8dn1BbxakpfiTVjP4nGYpFvK4urxF4pb6iji9jkk17Pps3lbcnjB7SKpTBmjM8iV99vQwfCd8oJRgQkrJObRmCxi+P8X3UvgxuhjgyShgFY13IwO3tZu0vpXS5jdkyVUQGHbG/bKyiOOGRG8gWR6DGAssf3kvZnGxH72jyk4AAi/glEP5fojSNcY/By1MJZb1QgwT1c+h/KjjtGBcjgBhSQ9jn1HY8wmzVSc+RAfNQB0HOCq3dxFFrhrKQNCOr/Dl6oxxBWSugoDTMmzzgdluswOT5rYnJDfXGGeAqYf5FqSHmcARSwQZjx96b8FgScUWaa4iM3/3kyPK8kZVcKF2MsqxW1ba+cRpGnTxIfITJtAwaAJENyEuQ/G2MPj0DFqUG3G3X+FbRGVuPgYGfsJCfLA23NsfM8ELfjPfz1PCiykNshliBFzay4oAafgQl0YdgRqtmTf7H/5FIgV+xiKwPUhCyU+vOKBNl+U71ur4xU=
  app: shielded-peak-40765
  on:
    repo: lightsage88/node-shopping-list-integration-tests
